org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

forge_version=52.1.3
forge_version_range=[52,)
loader_version_range=[52,)

mapping_channel=parchment
mapping_version=2024.11.17

mod_id=eschaton
mod_name=Eschaton
mod_license=MIT
mod_version=0.0.1
mod_group_id=net.twc
mod_authors=Rulft44, The_Encryption
mod_description=Beneath the Garden...

jei_version=19.22.1.316
